# We need super user privilages to excute docker
sudo: required

# Travis CI we need a copy of docker
services:
    - docker
# A series commnads run before tests are run.  We also tag and use a custom Docker file.
before_install:
    - docker build -t madkins2121/docker-react -f Dockerfile.dev .

    # A series of commands to run our test suite
script:
    - docker run madkins2121/docker-react npm run test -- --coverage --watchAll=false